version: '3.9'

name: spyxel-tunnel

services:
  spyxel:
    container_name: spyxel
    image: koalhack/spyxel
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    network_mode: host
    command: tunnel -url 127.0.0.1:8080
    stdin_open: true
    tty: true
